version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install aws-sam-cli

  build:
    commands:
      - sam build --template sam.yml

artifacts:
  files:
    - packaged.yaml
