version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install -g aws-sam-local

  build:
    commands:
      - npm install
      - sam build --template sam.yml

artifacts:
  files:
    - packaged.yaml
