Transform: 'AWS::Serverless-2016-10-31'
Parameters:
    SamMultipler:
        Description: "SAM multiplier. Make this really big to have a party :)"
        Type: "String"
    OriginUrl:
        Description: "The origin url to allow CORS requests from. This will be the base URL of your static SAM website."
        Type: "String"
Resources:
    GetSAMPartyCount:
        Type: AWS::Serverless::Function
        Properties:
            Handler: index.handler
            Runtime: nodejs14.x
            CodeUri: ./
            Environment:
                Variables:
                    SAM_MULTIPLIER: !Ref SamMultipler
                    ORIGIN_URL: !Ref OriginUrl
            Events:
              GetResource:
                Type: Api
                Properties:
                  Path: /sam
                  Method: get
    StudentCrud:
        Type: AWS::Serverless::Function
        Properties:
            Handler: index.handler
            Runtime: nodejs14.x
            CodeUri: ./src/student-crud/
            Events:
              CreateStudent:
                Type: Api
                Properties:
                  Path: /createStudent
                  Method: put
              ReadStudent:
                Type: Api
                Properties:
                  Path: /readStudent
                  Method: get
              UpdateStudent:
                Type: Api
                Properties:
                  Path: /updateStudent/{id}
                  Method: put
              DeleteStudent:
                Type: Api
                Properties:
                  Path: /deleteStudent/{id}
                  Method: delete

